feat: add runSync() helper function
ordo-one/package-concurrency-helpers pull request #45
Opened 2023-05-09 13:51 UTC by dimlio

## Description

Simple helper that allows running async closure in synchronous context.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. 

## Minimal checklist:

- [x] I have performed a self-review of my own code 
- [x] I have added `DocC` code-level documentation for any public interfaces exported by the package
- [x] I have added unit and/or integration tests that prove my fix is effective or that my feature works

2023-05-09 13:55 UTC, ser-0xff commented on Sources/ConcurrencyHelpers/RunSync.swift
> +    func nonthowing() async -> Result<T, Error> {
throwing?

2023-05-09 13:56 UTC, mr-swifter requested changes

2023-05-11 19:37 UTC, dimlio commented on Sources/ConcurrencyHelpers/RunSync.swift
> +    let result = Box<T?>(nil)
Sorry, don't see.
According to https://swiftinit.org/reference/swift-nio/2.39/niocore/niosendable `NIOSendable` is typealias to `Sendable`.

2023-05-15 07:48 UTC, dimlio commented on Sources/ConcurrencyHelpers/RunSync.swift
> +    let result = Box<T?>(nil)
Ah, thanks!

2023-05-23 08:07 UTC, mr-swifter approved these changes

2023-05-23 08:57 UTC, mr-swifter approved these changes

2023-05-23 09:04 UTC, merged